version: '3'
services:
  nginx-proxy:
    image: 'jwilder/nginx-proxy'
    ports:
      - '80:80'
      - '433:433'
    networks:
      - overlay 
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - nginx_data:/etc/nginx

  mariadb:
    image: 'docker.io/bitnami/mariadb:10.3-debian-10'
    networks:
      - overlay
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
      - MARIADB_USER=bn_mediawiki
      - MARIADB_DATABASE=bitnami_mediawiki
    volumes:
      - mariadb_data:/bitnami/mariadb

  postgresql:
    image: 'docker.io/bitnami/postgresql:11-debian-10'
    networks:
      - overlay
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
      - POSTGRESQL_USERNAME=bn_redmine
      - POSTGRESQL_DATABASE=bitnami_redmine
    volumes:
      -  postgresql_data:/bitnami/postgresql
      
  mediawiki:
    build: ./wiki
    ports:
      - '8080:8080'
    networks:
      - overlay
    environment:
      - MEDIAWIKI_DATABASE_HOST=mariadb
      - MEDIAWIKI_DATABASE_PORT_NUMBER=3306
      - MEDIAWIKI_DATABASE_USER=bn_mediawiki
      - MEDIAWIKI_DATABASE_NAME=bitnami_mediawiki
      - ALLOW_EMPTY_PASSWORD=yes
      - MY_DOMAIN
      - MEDIAWIKI_HOST=wiki.${MY_DOMAIN}
      - MEDIAWIKI_WIKI_NAME=${MY_MEDIAWIKI_WIKI_NAME}
      - VIRTUAL_HOST=wiki.${MY_DOMAIN}
      - VIRTUAL_PORT=8080
    volumes:
      - mediawiki_data:/bitnami/mediawiki
    depends_on:
      - mariadb
      - nginx-proxy

  redmine:
    # 1. init, OR
    image: bitnami/redmine:4-debian-10
    # 2. use plugins image
    #build: ./hub
    ports:
      - '3000:3000'
    networks:
      - overlay
    environment:
      - REDMINE_DB_POSTGRES=postgresql
      - REDMINE_DB_USERNAME=bn_redmine
      - REDMINE_DB_NAME=bitnami_redmine
      - MY_DOMAIN
      - VIRTUAL_HOST=hub.${MY_DOMAIN}
      - VIRTUAL_PORT=3000
    volumes:
      - redmine_data:/bitnami
    depends_on:
      - postgresql
      - nginx-proxy
        
  jupyter:
    build: ./jhub
    ports:
      - '8888:8888'
    networks:
      - overlay
    environment:
      - MY_DOMAIN
      - VIRTUAL_HOST=jhub.${MY_DOMAIN}
      - VIRTUAL_PORT=8888
    volumes:
      - jupyter_data:/home/jovyan/work
    depends_on:
      - nginx-proxy
    entrypoint: ["start.sh","jupyter", "lab"]
        
  web:
    image: 'nginx'
    ports:
      - '8081:80'
    networks:
      - overlay
    environment:
      - VIRTUAL_HOST=web.${MY_DOMAIN}
      - VIRTUAL_PORT=8081
      - NGINX_HOST=web.${MY_DOMAIN}
    volumes:
      - web_data:/usr/share/nginx/html
    depends_on:
      - nginx-proxy

volumes:
  mariadb_data:
    driver: local
  mediawiki_data:
    driver: local
  postgresql_data:
    driver: local
  redmine_data:
    driver: local
  jupyter_data:
    driver: local
  nginx_data:
    driver: local
  web_data:
    driver: local

networks:
  overlay:
  #host:
