version: '3'
services:
  nginx-proxy:
    image: 'jwilder/nginx-proxy'
    ports:
      - '80:80'
      - '433:433'
    networks:
      - overlay
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - ./br2_proxy_data/nginx/vhost.d:/etc/nginx/vhost.d
      - ./br2_proxy_data/nginx/certs:/etc/nginx/certs:ro
      - ./br2_proxy_data/nginx/html:/usr/share/nginx/html

  mariadb:
    image: 'docker.io/bitnami/mariadb:10.3-debian-10'
    networks:
      - overlay
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
      - MARIADB_USER=bn_mediawiki
      - MARIADB_DATABASE=bitnami_mediawiki
    volumes:
      - ./br2_mariadb_data:/bitnami/mariadb

  postgresql:
    image: 'docker.io/bitnami/postgresql:11-debian-10'
    networks:
      - overlay
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
      - POSTGRESQL_USERNAME=bn_redmine
      - POSTGRESQL_DATABASE=bitnami_redmine
    volumes:
      - ./br2_postgresql_data:/bitnami/postgresql
      
  mediawiki:
    build: ./wiki
    ports:
      - '8080:8080'
    networks:
      - overlay
    environment:
      - MEDIAWIKI_DATABASE_HOST=mariadb
      - MEDIAWIKI_DATABASE_PORT_NUMBER=3306
      - MEDIAWIKI_DATABASE_USER=bn_mediawiki
      - MEDIAWIKI_DATABASE_NAME=bitnami_mediawiki
      - ALLOW_EMPTY_PASSWORD=yes
      - BR_DOMAIN
      - MEDIAWIKI_HOST=wiki.${BR_DOMAIN}
      - VIRTUAL_HOST=wiki.${BR_DOMAIN}
      - VIRTUAL_PORT=8080
    volumes:
      - ./br2_mediawiki_data:/bitnami/mediawiki
    depends_on:
      - mariadb
      - nginx-proxy

  redmine:
    build: ./hub
    ports:
      - '3000:3000'
    networks:
      - overlay
    environment:
      - REDMINE_DB_POSTGRES=postgresql
      - REDMINE_DB_USERNAME=bn_redmine
      - REDMINE_DB_NAME=bitnami_redmine
      - BR_DOMAIN
      - VIRTUAL_HOST=hub.${BR_DOMAIN}
      - VIRTUAL_PORT=3000
    volumes:
      - ./br2_redmine_data:/bitnami
    depends_on:
      - postgresql
      - nginx-proxy
        
  jupyter:
    build: ./jhub
    ports:
      - '8888:8888'
    networks:
      - overlay
    environment:
      - BR_DOMAIN
      - VIRTUAL_HOST=jhub.${BR_DOMAIN}
      - VIRTUAL_PORT=8888
    volumes:
      - ./br2_jupyter_data:/home/jovyan/work
    depends_on:
      - nginx-proxy
    entrypoint: ["start.sh","jupyter", "lab"]
        
  test:
    image: 'nginx'
    ports:
      - '8081:80'
    networks:
      - overlay
    environment:
      - VIRTUAL_HOST=test.${BR_DOMAIN}
      - VIRTUAL_PORT=8081
    depends_on:
      - nginx-proxy

networks:
  overlay:
